import { useState, useMemo } from 'react';
import {
  Sidebar, TopBar, NotificationsPanel, roleConfigs,
  type RoleConfig,
} from '@/components/marketing-pr/components/layout/Sidebar';
import { notifications as initialNotifications, tasks as initialTasks } from '@/components/marketing-pr/data/mockData';
import type { Role, Notification, Task, TaskRequest, TaskTeam } from '@/components/marketing-pr/types';
import { CoverPage } from '@/components/marketing-pr/pages/CoverPage';
import { TeamTasksPage } from '@/components/marketing-pr/pages/team/TeamTasks';

// Marketing Head pages
import { BrandingReputation } from '@/components/marketing-pr/pages/marketing/BrandingReputation';
import { PRMediaManagement } from '@/components/marketing-pr/pages/marketing/PRMediaManagement';
import { CampaignManagement } from '@/components/marketing-pr/pages/marketing/CampaignManagement';
import { DigitalMarketingOverview } from '@/components/marketing-pr/pages/marketing/DigitalMarketingOverview';
import { TeamCoordination } from '@/components/marketing-pr/pages/marketing/TeamCoordination';
import {
  WorkflowCampaigns, WorkflowContentPage, WorkflowDashboard,
  WorkflowDigitalPage, WorkflowEventsPage, WorkflowAnalyticsPage,
} from '@/components/marketing-pr/pages/workflow/WorkflowPages';
import { initialWorkflowState, type WorkflowState } from '@/components/marketing-pr/data/workflowData';

// Digital Marketing pages
import {
  DigitalCampaignManagement, WebsiteManagement, SocialMediaManagement,
  SEOManagement, DigitalAnalytics, LeadGeneration,
} from '@/components/marketing-pr/pages/digital/DigitalPages';

// Content / Brand pages
import {
  ContentCreation, SocialMediaContentPage,
  ContentReviewApproval, ContentLibrary,
} from '@/components/marketing-pr/pages/content/ContentPages';

// Events & Outreach pages
import {
  EventManagement, SchoolOutreachPage, PartnershipCoordination,
  OutreachLeadGeneration,
} from '@/components/marketing-pr/pages/events/EventsPages';

// Mapping of team roles to their team name used in task assignment
const TEAM_NAME: Record<string, TaskTeam> = {
  digital: 'Digital Marketing Executive',
  content: 'Content & Brand Team',
  events: 'Events & Outreach Coordinator',
};


function App() {
  const [role, setRole] = useState<Role>('marketing-head');
  const [activePage, setActivePage] = useState('branding');
  const [sidebarCollapsed, setSidebarCollapsed] = useState(true);
  const [showNotifications, setShowNotifications] = useState(false);
  const [showRoleSwitcher, setShowRoleSwitcher] = useState(false);
  const [showCoverPage, setShowCoverPage] = useState(true);
  const [notifications, setNotifications] = useState<Notification[]>(initialNotifications);
  const [tasks, setTasks] = useState<Task[]>(initialTasks);
  const [requests, setRequests] = useState<TaskRequest[]>([]);
  const [workflowState, setWorkflowState] = useState<WorkflowState>(initialWorkflowState);

  const roleConfig: RoleConfig = useMemo(
    () => roleConfigs.find((r) => r.id === role) || roleConfigs[0],
    [role]
  );

  const handleNavigate = (pageId: string) => {
    setActivePage(pageId);
  };

  const handleSelectRole = (roleId: string) => {
    const newRole = roleId as Role;
    setRole(newRole);
    const newConfig = roleConfigs.find((r) => r.id === newRole);
    setActivePage(newConfig?.nav[0]?.id || 'branding');
    setShowCoverPage(false);
  };

  const handleSwitchRole = (newRole: Role) => {
    setRole(newRole);
    setShowRoleSwitcher(false);
    const newConfig = roleConfigs.find((r) => r.id === newRole);
    setActivePage(newConfig?.nav[0]?.id || 'branding');
    setShowCoverPage(false);
  };

  const handleMarkRead = (id: string) => {
    setNotifications((prev) => prev.map((n) => n.id === id ? { ...n, read: true } : n));
  };

  const handleMarkAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  };

  // Push real-time notifications generated by the task coordination workflow
  const handleNotify = (n: { title: string; message: string; role: Role }) => {
    setNotifications((prev) => [
      { id: `N${Date.now()}`, type: 'task', title: n.title, message: n.message, time: 'Just now', read: false, role: n.role },
      ...prev,
    ]);
  };

  // Filter notifications for current role
  const roleNotifications = notifications.filter(
    (n) => n.role === role || n.role === 'all'
  );
  const unreadCount = roleNotifications.filter((n) => !n.read).length;

  // Get breadcrumb and page title
  const currentNav = roleConfig.nav.find((n) => n.id === activePage);
  const pageTitle = showCoverPage ? 'Marketing & PR' : (currentNav?.label || 'Overview');
  const breadcrumb = showCoverPage ? ['Marketing & PR'] : [pageTitle];

  const renderPage = () => {
    switch (role) {
      case 'marketing-head':
        switch (activePage) {
          case 'digital-team-dashboard':
          case 'content-team-dashboard':
          case 'events-team-dashboard':
          case 'team-coordination':
            return <TeamCoordination tasks={tasks} setTasks={setTasks} requests={requests} setRequests={setRequests} onNotify={handleNotify} view={activePage} />;
          case 'workflow-dashboard': return <WorkflowDashboard state={workflowState} setState={setWorkflowState} onNotify={handleNotify} />;
          case 'workflow-campaigns': return <WorkflowCampaigns state={workflowState} setState={setWorkflowState} onNotify={handleNotify} />;
          case 'workflow-analytics': return <WorkflowAnalyticsPage state={workflowState} setState={setWorkflowState} onNotify={handleNotify} />;
          case 'branding': return <BrandingReputation />;
          case 'pr-media': return <PRMediaManagement />;
          case 'campaigns': return <CampaignManagement />;
          case 'digital-overview': return <DigitalMarketingOverview />;
          default: return <BrandingReputation />;
        }
      case 'digital':
        switch (activePage) {
          case 'workflow-digital': return <WorkflowDigitalPage state={workflowState} setState={setWorkflowState} onNotify={handleNotify} />;
          case 'my-tasks': return <TeamTasksPage teamName={TEAM_NAME.digital} tasks={tasks} setTasks={setTasks} requests={requests} setRequests={setRequests} onNotify={handleNotify} />;
          case 'digital-campaigns': return <DigitalCampaignManagement />;
          case 'website': return <WebsiteManagement />;
          case 'social-media': return <SocialMediaManagement />;
          case 'seo': return <SEOManagement />;
          case 'analytics': return <DigitalAnalytics />;
          case 'lead-gen': return <LeadGeneration />;
          default: return <DigitalCampaignManagement />;
        }
      case 'content':
        switch (activePage) {
          case 'workflow-content': return <WorkflowContentPage role="content" state={workflowState} setState={setWorkflowState} onNotify={handleNotify} />;
          case 'my-tasks': return <TeamTasksPage teamName={TEAM_NAME.content} tasks={tasks} setTasks={setTasks} requests={requests} setRequests={setRequests} onNotify={handleNotify} />;
          case 'content-creation': return <ContentCreation />;
          case 'social-content': return <SocialMediaContentPage />;
          case 'review': return <ContentReviewApproval />;
          case 'library': return <ContentLibrary />;
          default: return <ContentCreation />;
        }
      case 'events':
        switch (activePage) {
          case 'workflow-events': return <WorkflowEventsPage state={workflowState} setState={setWorkflowState} onNotify={handleNotify} />;
          case 'my-tasks': return <TeamTasksPage teamName={TEAM_NAME.events} tasks={tasks} setTasks={setTasks} requests={requests} setRequests={setRequests} onNotify={handleNotify} />;
          case 'events': return <EventManagement />;
          case 'school-outreach': return <SchoolOutreachPage />;
          case 'partnerships': return <PartnershipCoordination />;
          case 'outreach-leads': return <OutreachLeadGeneration />;
          default: return <EventManagement />;
        }
      default:
        return <BrandingReputation />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {!showCoverPage && (
        <Sidebar
          role={roleConfig}
          activePage={activePage}
          onNavigate={handleNavigate}
          onSwitchRole={() => setShowCoverPage(true)}
          collapsed={sidebarCollapsed}
          onToggleCollapse={() => setSidebarCollapsed(!sidebarCollapsed)}
        />
      )}

      {!showCoverPage && !sidebarCollapsed && (
        <div
          className="fixed inset-0 z-40 bg-slate-900/25"
          onClick={() => setSidebarCollapsed(true)}
          aria-hidden="true"
        />
      )}

      <div>
        <TopBar
          breadcrumb={breadcrumb}
          pageTitle={pageTitle}
          role={roleConfig}
          notifications={{ unread: unreadCount }}
          onToggleNotifications={() => setShowNotifications(!showNotifications)}
          sidebarCollapsed={sidebarCollapsed}
          onToggleSidebar={() => setSidebarCollapsed(!sidebarCollapsed)}
          noSidebar={showCoverPage}
        />

        <main className="p-6 max-w-[1600px] mx-auto">
          {showCoverPage
            ? <CoverPage roles={roleConfigs} onSelectRole={handleSelectRole} sidebarCollapsed={sidebarCollapsed} />
            : renderPage()}
        </main>
      </div>

      <NotificationsPanel
        open={showNotifications}
        onClose={() => setShowNotifications(false)}
        notifications={roleNotifications}
        onMarkRead={handleMarkRead}
        onMarkAllRead={handleMarkAllRead}
      />

      {/* Role Switcher Modal */}
      {showRoleSwitcher && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={() => setShowRoleSwitcher(false)} />
          <div className="relative w-full max-w-lg bg-white rounded-xl shadow-2xl animate-fade-in">
            <div className="px-6 py-4 border-b border-slate-200">
              <h2 className="text-lg font-semibold text-slate-800">Switch Role</h2>
              <p className="text-sm text-slate-500 mt-0.5">Select a role to view its workspace</p>
            </div>
            <div className="p-4 space-y-2">
              {roleConfigs.map((r) => (
                <button
                  key={r.id}
                  onClick={() => handleSwitchRole(r.id)}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg border transition-colors text-left ${
                    role === r.id ? 'border-blue-500 bg-blue-50' : 'border-slate-200 hover:bg-slate-50'
                  }`}
                >
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${r.color}`}>
                    {r.icon}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-slate-800">{r.name}</p>
                    <p className="text-xs text-slate-500">{r.nav.length} modules available</p>
                  </div>
                  {role === r.id && (
                    <span className="ml-auto text-xs font-medium text-blue-600">Current</span>
                  )}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}

export default App;
